version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: yearly
    open-pull-requests-limit: 0
    target-branch: "develop"
    labels:
      - dependabot
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"